function Hd = FPB_Hamming
%FPB_HAMMING Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 23-May-2024 19:05:45

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 12529;  % Sampling Frequency

N    = 60;       % Order
Fc1  = 710;      % First Cutoff Frequency
Fc2  = 750;      % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
fvtool(Hd)